### ISSUE TITLE
interact_text on Windows 10 - Shift causes Custom Error

### ISSUE THREAD

**Issue by Archina** [mitsuhiko/dialoguer#110]
I seem to get a `Custom { kind: NotConnected, error: "Not a terminal" }` whenever I try to use shift together with a letter on Windows 10. This happens also when I run the dialoguer input example on the same machine.

This does not seem to depend on the terminal. I have the error in PowerShell as well as in the regular cmd.

I also tried to use an older version of dialogue `0.7.1` with the same result.

The terminal consumes all normal characters and breaks as soon as the `shift + character` is encountered.

**Comment by Archina** [comment]
So i tried to trace down the bug further. It seems this derives from the dependency `console`. To be more detailed the `key_from_key_code` function in the `windows_term.rs` does not seem to handle `winapi::um::winuser::VK_SHIFT => Key::Shift`. Looking at the code however it seems okay to return `Key::Unknown` there. However, returning `Ok(Key::Unknown)` as well when `self.is_tty` is `false` seems wrong. It may be beneficial to instead return an actual `Err` in that case or to resort to an alternative enum value for `Key`.

**Comment by pksunkara** [comment]
Have you tried with latest dialouger 0.8.0?

**Comment by Archina** [comment]
I am quite sure that I was using the master branch for trying out the examples.

On my own project, I was using "0.8.0"

**Comment by spenserblack** [comment]
I'm also still experiencing this (see mitsuhiko/console#83 for issue I opened).

To reproduce here:

```bash
git clone https://github.com/mitsuhiko/dialoguer.git
cd dialoguer
git checkout 0.8.0
cargo run --example input
# press shift key
```

**Comment by pksunkara** [comment]
Fixed by https://github.com/mitsuhiko/console/pull/96

**Comment by lucasfernog** [comment]
Hey @mitsuhiko , nice work on this lib :) I love it and used it on several projects. When is this fix planned to be released?

Thank you :)

**Comment by pksunkara** [comment]
We have some breaking changes in console which means it will take a bit more time to publish it so that we have more chance to include other breaking changes.

**Comment by Sloff** [comment]
I'm also experiencing this issue, using version 0.8.0
