### ISSUE TITLE
Abort a dialog

### ISSUE THREAD

**Issue by piegamesde** [mitsuhiko/dialoguer#115]
Sometimes, I ask the user a question, but then something happens and that question becomes obsolete before it got answered. I don't think `dialoguer` can handle this yet(?), since the `interact` method is blocking.

**Comment by pksunkara** [comment]
Yup.

**Comment by piegamesde** [comment]
Well, consider this a feature request then.

**Comment by pksunkara** [comment]
I would consider it as out of scope for this project. I would recommend you to play with much more lower level libraries.
