### ISSUE TITLE
Allow user to filter select view (fuzzy select)

### ISSUE THREAD

**Issue by gleich** [mitsuhiko/dialoguer#118]
Hello! Thank you so much for this awesome crate! It is super helpful in one of the cli applications I am currently building. It would be great if the user could type part of an item to filter down the list for a select view. This would be especially great for long lists of items. Thank you again and I would love to hear your thoughts on this!

**Comment by pksunkara** [comment]
See #79

**Comment by Matt-Gleich** [comment]
Ah ok, sorry for the duplicate!

**Comment by pksunkara** [comment]
This is not duplicate. That is a PR.

**Comment by pksunkara** [comment]
Fixed now.
