### ISSUE TITLE
zeroize 1.4 requires rustc 1.51

### ISSUE THREAD

**Issue by matthiasbeyer** [mitsuhiko/dialoguer#123]
Hi,

the build of my crate just broke because dialoguer depends on "zeroize" in "1.1.1", but zeroize 1.4 updates the MSRV to 1.51.0 (they really should have done a "2.0" release, not 1.4!).

Not your fault at all, of course, just wanted to let you know that your crate automatically is now MSRV 1.51.0! :laughing:

**Comment by pksunkara** [comment]
Thanks for letting us know.
