### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by gleich** [mitsuhiko/dialoguer#127]
Hello! I am super glad to see that #124 got merged but I don't see a new release yet. No rush, I totally understand that this is a volunteer project. I was just wondering if you haven't gotten around to publishing a new version or if something else needs to happen before it can get released. In the meantime, I was going to just pull from the git repo directly but I get the error ``no FuzzySelect in the root`` when trying to import it. I am very much new to rust so it could be something I am doing wrong.

**Comment by pksunkara** [comment]
Add `features = ["fuzzy-select"]` to the dependency line. [Learning](https://doc.rust-lang.org/cargo/reference/features.html)

**Comment by gleich** [comment]
Ok, thank you! I know about features but didn't know that `FuzzySelect` would only be exposed using it. I'm assuming that this will be documented in the official documentation, right?

**Comment by gleich** [comment]
So I was able to get it all working but I forgot that you can't publish to crates.io if the dep is specified via a path. This means that I need a new released version to publish. Any timeline on when a new version might be out?

**Comment by pksunkara** [comment]
I will publish once the issues slated for 0.9.0 are fixed. Here's the milestone https://github.com/mitsuhiko/dialoguer/milestone/1
