### ISSUE TITLE
Limit the number of visible options in fuzzy select

### ISSUE THREAD

**Issue by garrettmaring** [mitsuhiko/dialoguer#134]
it would be great to have some sort of pagination when using `FuzzySelect` with many (100-1000s) of items

**Comment by pksunkara** [comment]
FuzzySelect uses search text to filter items. You shouldn't need pagination.

**Comment by garrettmaring** [comment]
well, fuzzy style searching is very useful for very large collections. when using FuzzySelect with many items, the CLI is pushed "up" inside the terminal and it is rather unwieldy.

it'd be a fairly clean UI to be able to have paginated results / list (say 100 items match the fuzzy input after a few characters) to be able to navigate larger lists in addition to searching for them.

**Comment by danieleades** [comment]
> Fuzzy select should not have paging.

Why is this?

**Comment by pksunkara** [comment]
Because that is what fuzzy searching means? It's kind of like an autocomplete. Where the suggestions show up to fill the place instead of just showing all the options available. Please correct me if I am mistaken.

**Comment by danieleades** [comment]
> Because that is what fuzzy searching means? It's kind of like an autocomplete. Where the suggestions show up to fill the place instead of just showing all the options available. Please correct me if I am mistaken.

i thought the use case described above was reasonably compelling. namely that at an intermediate search stage, when filtering has been applied, but there are still a large number of entries, being able to scroll through the list could be preferable to having to continue to extend the search term. For example, you might search a prefix representing a collection of objects without necessarily knowing the members of that set.

But i'm speculating. I don't have a particular use-case in mind. Do you lose any other functionality by enabling paging for the fuzzy search? is there a cost associated with this?

**Comment by pksunkara** [comment]
I don't mind implementing paging in fuzzy_select but I don't see how it is possible without overcomplicating the keypress semantics in the lib.

If you look at `Select` prompt [here](https://github.com/mitsuhiko/dialoguer/blob/master/src/prompts/select.rs#L310-L315), we the right and left arrow keys to change pages.

If you look at `FuzzySelect` prompt [here](https://github.com/mitsuhiko/dialoguer/blob/master/src/prompts/fuzzy_select.rs#L203-L207), we use them to move on the input line (similar to how `Input` prompt behaves)

**Comment by danieleades** [comment]
That makes sense.
