### ISSUE TITLE
dialoguer::Input doesn't accept an empty string

### ISSUE THREAD

**Issue by samuela** [mitsuhiko/dialoguer#15]
If you open a `dialoguer::Input` and just hit enter, the terminal will insert a newline but won't actually end the prompt and return the empty string as expected.

**Comment by samuela** [comment]
https://github.com/mitsuhiko/dialoguer/blob/master/src/prompts.rs#L215 looks like the culprit

**Comment by nicohman** [comment]
Using the allow_empty method I added in 56b3c2a8f165efed8b70cfa180391db13c433e60, you can now permit empty strings to be returned from an Input, though it isn't the default.
