### ISSUE TITLE
Phone validator too strict

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/dialoguer#16]
The phone validator on master is currently too strict. It assumes certain input formats that are not met in the real world in some countries. (eg: Austria typically has `+43 XXX YY YY YYY` or `+43 XXX YYYY YYY`.

**Comment by mitsuhiko** [comment]
I think it might be a better idea to just remove the pre-built validators for now.

**Comment by nicohman** [comment]
Yeah, that probably makes sense. I removed them in 56a37a4ebc1faf3e35404a10c30198047bba3aaa and created a new branch, `prebuilt`, so that they can be worked on and added to a later release.

**Comment by mitsuhiko** [comment]
This one probably conflicts ATM but I wonder if this is not a better interface: https://github.com/mitsuhiko/dialoguer/pull/17
