### ISSUE TITLE
Add option to truncate long lines

### ISSUE THREAD

**Issue by NfNitLoop** [mitsuhiko/dialoguer#161]
Summary
----------

It would be nice if Dialoguer structs had an option to truncate long lines to the width of the terminal.[^1] This may often be desired behavior, and also helps protect against issues like in https://github.com/mitsuhiko/dialoguer/issues/20.

[^1]: OR, in the case of Windows, the reported terminal width - 1, due to the Windows Terminal wrapping bug.

Context
---------

I came here to report that Select and others are not rendering correctly in Windows Terminal. I'm not sure if that's a bug with Dialoguer, or the Windows Terminal bug I mentioned over in https://github.com/mitsuhiko/dialoguer/issues/20#issuecomment-1008176598, but this feature would both be nice and also protect against that.

**Comment by NfNitLoop** [comment]
IMO, due to the unexpected behavior long/wrapping lines can introduce, my personal preference would be for this option to default to on/true.

**Comment by pksunkara** [comment]
This is what #20 is about. Making sure output plays nice with all kinds of terminal sizes.

I am going to close this as duplicate. Please provide any arguments for needing a separate issue.
