### ISSUE TITLE
docs for fuzzy select

### ISSUE THREAD

**Issue by stumash** [mitsuhiko/dialoguer#184]
fuzzy select is not present in the docs
would be nice to put it in

**Comment by stumash** [comment]
https://github.com/mitsuhiko/dialoguer/blob/master/src/prompts/fuzzy_select.rs#L34-L36

is the problem here simply that there is a newline here that shouldn't be here?

**Comment by pksunkara** [comment]
This was recently fixed by a PR. Just hasn't been published.

**Comment by stumash** [comment]
you should publish though cuz this feature is fucking sick

**Comment by stumash** [comment]
want me to put a PR for an auto-pubish github action? you can fill in the secrets or whatever
