### ISSUE TITLE
Issue with FuzzySelect - doesn't act like in example

### ISSUE THREAD

**Issue by pulanski** [mitsuhiko/dialoguer#210]
I'm not sure if this is a bug or if I'm missing a specific feature flag when trying to get this working.

Below are two gifs showing the differing usage:

One shows the example usage of fuzzy-select, which I'm running from a cloned version of this repo.

https://user-images.githubusercontent.com/63331369/181647554-4335ac9c-894e-493c-8dda-7d49d27cc5b8.mov

Other is in fresh repo where I've done `cargo add dialoguer --features fuzzy-select`

https://user-images.githubusercontent.com/63331369/181648110-1b385ca9-d5de-4526-843d-c2831f59e111.mov

Specifically, I'm interested in the functionality where the currently selected item is highlighted in cyan, as can be seen in the source code. I'm not sure if this is a bug, or if I simply need to add another feature reference in my Cargo.toml. Any help would be greatly appreciated, thanks.

Additionally, here is a small reproduction of the issue for reference, https://github.com/pulanski/minimum-repo-dialoguer-bug

**Comment by pksunkara** [comment]
Thats because it's not published. I just did that though.

**Comment by pulanski** [comment]
Awesome, thanks.
