### ISSUE TITLE
Please publish the latest

### ISSUE THREAD

**Issue by Rauno56** [mitsuhiko/dialoguer#23]
Awesome crate. Thanks!
I was struggling with using it without realizing that the current source is not all published with `0.4.0`.

[Commit that I'm personally after](https://github.com/mitsuhiko/dialoguer/commit/6cbd4359a6b45a308ed4b14bf12268a72e15e4c3), which is, as I now see - the only thing missing from. `0.4.1`? `1.0.0`?

**Comment by mitsuhiko** [comment]
Done!
