### ISSUE TITLE
Panic on invalid navigation key input.

### ISSUE THREAD

**Issue by K41eb** [mitsuhiko/dialoguer#29]
Don't pay attention to the title, I can't describe the issue with one sentence.

I just created a select menu with:
```
let choice = dialoguer::Select::new().with_prompt(&menu.prompt)
      .items(&menu.get_items_labels()[..])
      .interact()
      .unwrap();
```

`menu` is just a struct I made to hold all of the menu information in one place.

This code yields a menu with no cursor to start with. Using 'up' and 'down' arrow keys will spawn the cursor at the top or bottom, once the cursor has spawned everything is handled correctly, typing 'A', 'left arrow' or anything else doesn't do anything. Works as intended.

The issue arises when the cursor hasn't spawned yet. Using anything else than the 'up' or 'down' arrow will:
- on the first keypress: erase the menu options.
- on the second keypress: panic with the following error
```
thread 'main' panicked at 'attempt to multiply with overflow', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/dialoguer-0.4.0/src/select.rs:208:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Note that using an 'up' or 'down' arrow key after the first invalid keypress that erases the menu will bring the menu back and work like intended.

EDIT: Fixed the menu method, it was with a `Select` menu, not `Checkboxes`.

**Comment by TheDan64** [comment]
This also happens with `Select`

**Comment by K41eb** [comment]
Oh, my bad, it was with a Select menu yes, I didn't even try the `Checkboxes` menu.

**Comment by mitsuhiko** [comment]
This is fixed.
