### ISSUE TITLE
Bash-style prompt (accepts arrow keys)?

### ISSUE THREAD

**Issue by TheDan64** [mitsuhiko/dialoguer#30]
What I'd like to do is similar to bash where you can press up/down to load previous inputs or start typing. Does `dialoguer` support anything like this? I haven't been able to find a way to get `Input` and `read_key` to work together in such a seamless way.

I think it would need some way to report non-char keys until the prompt is entered. And the prompt should be redrawable, either automatically (based on char inputs) or internally (ie if I want to load a prompt from history/as a response from non char key input)

**Comment by lilianmoraru** [comment]
That would mean that `dialoguer` needs to save a history of your inputs.
There is a less intrusive alternative: searching through options, but no tracking of your previous inputs.
If the alternative is ok, there is a FuzzySearch alternative: https://github.com/slaterb1/dialoguer
`cargo run --release --example fuzzyselect`

**Comment by TheDan64** [comment]
Fuzzyselect isn't really what I'm looking for. Couldn't the user be responsible for providing the history?

**Comment by pksunkara** [comment]
You might want to use `rustyline` crate in that case since it supports history like what you are asking. Or if you want a custom interaction, you can build one out of `console` crate.

I am considering this as out of scope for dialoguer.
