### ISSUE TITLE
Example of validate_with

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [mitsuhiko/dialoguer#36]
Hello there 😄 Thank you for contributing to Open Source. I am really enjoying using your library. I have created a function that given a String returns a `Result<bool, Error>` depending if a text input follows some criteria. Recently, I found that your library supports a `validate_with` function. Would it be easy to provide me with a usage example of `validate_with`?

**Comment by vallentin** [comment]
I added a `validate_with` example in #41.

The general gist is:

```rust
Input::<String>::new()
    .with_prompt("Enter email")
    .validate_with(|input: &str| -> Result<(), &str> {
            if input.contains('@') {
                Ok(())
            } else {
                Err("This is not a mail address")
            }
        });
```

If the validate function returns `Ok(())` then it is valid, otherwise it is invalid, and dialoguer will display the error.
