### ISSUE TITLE
Don't force : character in prompt

### ISSUE THREAD

**Issue by acheronfail** [mitsuhiko/dialoguer#4]
I think it would be nicer if this crate didn't force `":"` at the end of the prompts.

An example use case is if one wants to make an input with a different prompt, or password input with an icon, etc.

```bash
# Allow a custom prompt character, like ">"
Username >>

# Alternatively have an icon at the password prompt:
Password: 🔑
```

**Comment by nicohman** [comment]
You could already do this using a custom theme, but I added CustomPromptCharacter theme in a94e7f91cc3131a4df1410562ca9d24962bcc54c to make it slightly easier -- see `examples/prompt_character.rs` for an example of how to use it.
