### ISSUE TITLE
Optional interact for input

### ISSUE THREAD

**Issue by kegesch** [mitsuhiko/dialoguer#46]
I was wondering why there is no `interact_opt` on the `input` prompt. Is there a specific reason or just not implemented yet?

**Comment by kegesch** [comment]
@SirWindfield i think at the moment there even can't be an empty string. It has to be at least a whitespace or am I wrong? But yeah returning `None` would be nice.

**Comment by SirWindfield** [comment]
No, an empty string works currently. You just have to enable it explicitly:

https://github.com/SirWindfield/git-cm/blob/47de71b9e7245e12c4b881a8aef0b5b61b272ee8/src/questions.rs#L53-L58

**Comment by pksunkara** [comment]
I think I will close this issue unless anyone objects.

**Comment by SirWindfield** [comment]
Why closing it? It's a feature request, a new method that returns an Option instead of an empty String 🤔
