### ISSUE TITLE
Input does not support arrow navigation

### ISSUE THREAD

**Issue by oOBoomberOo** [mitsuhiko/dialoguer#48]
![](https://i.imgur.com/ObUUeCZ.png)
Pressing arrow key in `Input` will cause these characters to appear instead of moving cursor like expected.

**Comment by SirWindfield** [comment]
On that note, popular shortcuts like `ctrl-a`, `ctrl-e`, `alt-b`, `alt-e` do not work as well. What has to be done to make this work? Is the underlying implementation available in `console`?

**Comment by pksunkara** [comment]
Yeah, `console` needs some work and then dialoguer.
