### ISSUE TITLE
PasswordInput containing password buffers has to be zeroized on `drop`

### ISSUE THREAD

**Issue by fadeevab** [mitsuhiko/dialoguer#49]
This is a common security problem: once password appears in the memory, it stays there unless it is explicitly erased. The problem is solved using a type which erases buffer on `drop`. 

There is a crate `rpassword` which does only one function: it prompts for a password, reads the input, but all password buffers are erased on `drop`.

@mitsuhiko I saw your blog, seems like you're alive :) Is there a sense to provide a PR so you will review it?

There are 2 options to implement it: using the `secrecy` crate which implements `SecretString` and it is pretty stable (it is used in Rust Crypto), or implement own type, but I would suggest `secrecy`. (Tech detail: it's not enough to fill the buffer with zeroes, because compiler will optimize `memset` in the end of the function as a redundant peace of code).

Thank you for a feedback!

**Comment by ofadieiev** [comment]
@mitsuhiko

About this issue: only the internal **confirmation** password must be erased, so the dialoguer API stays the same. The returned password can be boxed into any zeroizable container by user. So don't worry about backward compatibility. Would you be ok about such scenario?

**Comment by fadeevab** [comment]
@mitsuhiko

About this issue: only the internal confirmation password must be erased, so the dialoguer API stays the same. The returned password can be boxed into any zeroizable container by user. So don't worry about backward compatibility. Would you be ok about such scenario?

**Comment by pksunkara** [comment]
@fadeevab I am willing to accept a PR.

**Comment by fadeevab** [comment]
@pksunkara Cool! Give me a time to prepare a PR then.
