### ISSUE TITLE
PasswordInput give visual confirmation with asterisks when password entered?

### ISSUE THREAD

**Issue by bradwood** [mitsuhiko/dialoguer#50]
Is there a way I can get a visual indicator when the password is typed in, like a `*` for every character typed at the prompt?

**Comment by fadeevab** [comment]
@bradwood  Basically, this approach to not show the stars is traditional for Linux: all such packages doesn't show the stars. The security concern behind this is that the count of "*" shows the length of your password which makes easier to guess one via eyesdropping, it narrows down the scope of bruteforcing as well.

**Comment by fadeevab** [comment]
@bradwood Maybe it could be some configurable feature though 🤷‍♂️ Either way you should know that the mainter doesn't respond here usually.

**Comment by bradwood** [comment]
It does not appear to be configurable from what I can tell. I'll probably find another library, or code something up myself, if this isn't maintained.  Thanks for your help.

**Comment by pksunkara** [comment]
What @fadeevab said is correct. If you want to make it configurable, I am willing to accept a PR, but otherwise I am closing this issue.
