### ISSUE TITLE
term::read_key vs term::read_line

### ISSUE THREAD

**Issue by rjwalters** [mitsuhiko/dialoguer#57]
I'd like to be able to manage user input by keystroke as it is being collected, so that I can avoid displaying unprintable characters and detect ESC as a cancel action.

I'm not sure what would be the best way to accomplish this. One solution would be to add a new flavor of `read_line` to the `console` crate and a new prompt type to `dialoguer`. Is this something you think is worthwhile? It would require some coordination of PRs between `dialoguer` and `console`.

My current solution is to replace the `read_line` calls in `prompt/input`:

``` rust
// We'd like to hide non-ascii keystrokes and also offer "ESC" as a way for the user to
// cancel input... but console::term doesn't allow this. Perhaps new public functions
// could be added to the console library but this would require us to patch
// both dialoguer and console.  Instead I've moved the internals of console's
// read_line_initial_text fn here and modified it to suit our purpose.

let mut chars: Vec<char> = Vec::new();

if let Some(initial) = self.initial_text.as_ref() {
    term.write_str(initial)?;
    chars = initial.chars().collect();
}

loop {
    match term.read_key()? {
        Key::Backspace => {
            if chars.pop().is_some() {
                term.clear_chars(1)?;
            }
            term.flush()?;
        }
        Key::Escape => {
            chars = vec!['\x1B'];
            break;
        }
        Key::Enter => break,
        Key::Char(chr) => {
            if chr.is_ascii_alphanumeric() || chr.is_ascii_whitespace() {
                chars.push(chr);
                let mut bytes_char = [0; 4];
                chr.encode_utf8(&mut bytes_char);
                term.write_str(chr.encode_utf8(&mut bytes_char))?;
                term.flush()?;
            }
        }
        _ => (),
    }
}

let input = chars.iter().collect::<String>();
```

I'm sure the ESC handling sequence could be a lot cleaner but this seems to be working...

**Comment by pksunkara** [comment]
I was actually thinking of doing this in the upcoming refactor of input prompt to fix #48. Would really appreciate if you can send a PR. AFAIK, you don't really need to edit console, everything is available to do this.

**Comment by rjwalters** [comment]
Unfortunately this approach seems to cause problems with pasting input for linux terminals. I'll see if I can figure it out and will prepare a PR if I find a solution.

**Comment by rjwalters** [comment]
seems like it might work with a `term::buffered_stderr`

**Comment by rjwalters** [comment]
So patching console does fix the pasting issue... but I'm not sure if this will cause other problems. This seems potentially related to https://github.com/mitsuhiko/console/issues/36
