### ISSUE TITLE
Is it possible to not output anything after a password prompt ?

### ISSUE THREAD

**Issue by lud** [mitsuhiko/dialoguer#59]
Currently, after prompting for a password, I have the following output (with no theme):

```
Master key: [hidden]
```

Is it possible to disable this output ? Even if there is a blank line that would be ok.

Thank you.

**Comment by pksunkara** [comment]
We can edit the `SimpleTheme` to add a new setting regarding this.

**Comment by lud** [comment]
This is very low priority but that would be nice !

**Comment by pksunkara** [comment]
It should be an easy fix, would appreciate a PR.

**Comment by lud** [comment]
I am a total noob with Rust but i'll give it a go :)

**Comment by pksunkara** [comment]
You can now customize this in the theme by overriding `format_password_prompt_selection`
