### ISSUE TITLE
Not clear different between interact_on and interact_text_on in Input

### ISSUE THREAD

**Issue by szarykott** [mitsuhiko/dialoguer#63]
While enhancing documentation I had hard time understanding what is the difference between `interact_on` and `interact_text_on` in `Input` prompt (and I failed)

Solution would be to either:
* remove one of those,
* describe clearly use-cases and differences between them in the docs. I couldn't do it as it was unclear for me.

**Comment by pksunkara** [comment]
It is recently added. Interact text only takes text keys while the normal interact allows all kinds of input Ctrl, arrow etc

**Comment by SzaryKot** [comment]
Thank you! I might create a new PR to improve documentation about it. Are both versions of `interact` planned to be preserved in future crate's version?

**Comment by pksunkara** [comment]
Yes, both will stay.

**Comment by szarykott** [comment]
Created a pull request. If it is merged, please close the issue.
