### ISSUE TITLE
Confirm with no default

### ISSUE THREAD

**Issue by mcginty** [mitsuhiko/dialoguer#64]
In a CLI-based wizard, it's quite easy to accidentally hit the Enter key an accidental extra time and mistakenly select a default confirmation you wanted to change.

As a feature, it would be nice not only to change the default, but to disable a default all-together, such that you *must* type a "y" or "n" before the prompt returns.

**Comment by SirWindfield** [comment]
Sounds cool! Maybe either as `no_default()` or `explicit_input()` method calls on the builder pattern?

**Comment by pksunkara** [comment]
PRs are welcome. Adding a `confirm()` on the prompt builders should be ok.

**Comment by pksunkara** [comment]
So, the new 0.7.0 release will contain `Confirm` with no default value by default.
