### ISSUE TITLE
panic: "attempt to divide by zero" when an empty list of items is passed to Select

### ISSUE THREAD

**Issue by wgoodall01** [mitsuhiko/dialoguer#71]
If you pass `Select` an empty list of items, and don't have paginated output enabled, you get a division by zero panic at this line:

https://github.com/mitsuhiko/dialoguer/blob/37b460a2e34c45174b39c900a2c2609657c0d91b/src/prompts/select.rs#L255

I'm using `dialoguer` 0.6.2.

**Comment by pksunkara** [comment]
The things is you should not be passing 0 items to the select prompt at all. I could have a nicer panic message but it still would result in a panic. Unless someone can convince me of a use case where select should be working with 0 items.

**Comment by SirWindfield** [comment]
> Unless someone can convince me of a use case where select should be working with 0 items.

Not exactly, but a simple `assert!(!selections.is_empty(), "selection list cannot be empty!")` should do the trick imo.

**Comment by pksunkara** [comment]
Okay with me. Please send a PR. Also, please check other situations like this too instead of only select.
