### ISSUE TITLE
Cursor disappears when using SIGINT (ctrl-c).

### ISSUE THREAD

**Issue by SirWindfield** [mitsuhiko/dialoguer#77]
I use this crate over at https://github.com/SirWindfield/git-cm and a user opened an issue stating that after they press ctrl-c, their cursor disappears:

https://github.com/SirWindfield/git-cm/issues/40

I think this is a bug/oversight inside of dialoguer or console and not my crate to be honest 🤔

**Comment by s2terminal** [comment]
I just have the same problem. This is reproduct code. (`dialoguer = "0.6.2"`)

```rust
fn main() {
    if Confirm::new().with_prompt("Do you want to continue?").interact().unwrap() {
        println!("Looks like you want to continue");
    } else {
        println!("nevermind then :(");
    }
}
```

**Comment by jgilchrist** [comment]
@SirWindfield @s2terminal At the moment I'm working around this with a combination of the `ctrlc` and `console` crates:

```
ctrlc::set_handler(move || {
    let term = console::Term::stdout();
    let _ = term.show_cursor();
})?;
```

**Comment by pksunkara** [comment]
This is intentional. Ctrl-c and other stuff are not supposed to be handled by dialoguer when prompting.

**Comment by SirWindfield** [comment]
Fair enough. I was pretty sure that dialoguer did actually use ctrl-c handling but after checking the crates it seems that I was wrong :) 

I'll close this then.

**Comment by Ekleog** [comment]
@SirWindfield Maybe it'd make sense to reopen this as a documentation issue to let people know of this limitation? IMO this should be documented in the front page of dialoguer, as I recently hit it too with https://github.com/Ekleog/nixpkgs-check/issues/20

**Comment by SirWindfield** [comment]
No need to re-open. Documentation only changes are probably fine with a PR only :) 

<sub>I mean technically this issue is resolved. But I do agree that a notice inside the docs/readme would be good!</sub>

**Comment by chenyan2002** [comment]
> This is intentional. Ctrl-c and other stuff are not supposed to be handled by dialoguer when prompting.

@pksunkara I understand `dialoguer` doesn't want to insert any signal handler. But would it be cleaner to intercept Ctrl+C here: https://github.com/console-rs/dialoguer/blob/master/src/prompts/select.rs#L236? 

`dialoguer` sets `term.hide_cursor()` at the beginning, it makes sense to restore the cursor up on seeing ctrl+c.
