### ISSUE TITLE
[feature request] add optional description to all dialogues

### ISSUE THREAD

**Issue by wucke13** [mitsuhiko/dialoguer#85]
Hi, I'm currently building an interactive configuration editor, and I would like to display some more information to the user up on input. I'll attach an example on how that could look (just imagine a normal `MultiSelect` on the left side):

![](https://user-images.githubusercontent.com/20400405/93691947-ca363f00-faec-11ea-8727-260a467ea056.png)

What do you think, can this feature be added to dialoguer?

**Comment by pksunkara** [comment]
We don't use ncurses and we don't use the full screen. This is just normal ANSI escape code manipulation. If you want full fledged TUI, please look at other libs.

**Comment by wucke13** [comment]
Ok, thank you for the statement :)
