### ISSUE TITLE
[feature request] add multi field editor

### ISSUE THREAD

**Issue by wucke13** [mitsuhiko/dialoguer#86]
Hi, something else: I would like to have a multi field editor. Just multiple `Input` fields (if possible in more than one column, to save line-space) which can be cycled by arrow up/arrow down and tabulator. What do you think about such a feature?

**Comment by pksunkara** [comment]
Can you please explain more on how this would work etc..?

**Comment by wucke13** [comment]
I imagine something like this: multiple normal inputs, organized row by row in a multicol design which makes clever use of the available terminal width. Focus can be cycled through the fields by tab and arrow up/arrow down. 

However, I realized that this might come closer to a full TUI lib and less to a dialoguer. Currently I'm investigating whether it is the right step to ditch dialoguer for cursive, as this feature becomes out of scope for dialoguer eventually. That however is not my decision to make :smile: 

Is it more clear now?

**Comment by pksunkara** [comment]
Yeah, it is out of scope for this library.
