### ISSUE TITLE
Terminal cursor is hidden on macOS

### ISSUE THREAD

**Issue by camelid** [mitsuhiko/dialoguer#92]
The `Select` prompt hides my terminal cursor when I'm selecting the option (which makes sense) but it doesn't restore it after execution, which is frustrating.

**Comment by camelid** [comment]
I verified that printing `'\x1b[?25h'` to the screen shows my cursor again, so I don't think it's an issue with my terminal.

**Comment by pksunkara** [comment]
Are you cancelling in the middle of the execution?

**Comment by camelid** [comment]
It seems like that might have been the cause. Is there any way to restore the cursor if the program is interrupted?

**Comment by pksunkara** [comment]
No, it shouldn't be the scope of the dialoguer but the program which should handle ctrl-c.
